plugins {
    id 'java-library'
}

group = 'io.jcrpc'
version = '0.5.0'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Xlint:-options']
}

jar {
    manifest {
        attributes('Implementation-Title': project.name,
                   'Implementation-Version': project.version)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api 'com.klinec:jcardsim:3.0.5.9'
}
